language: ruby
rvm:
  - 2.4.2

before_install:
  - TFVERSION=0.11.8 wget https://releases.hashicorp.com/terraform/${TFVERSION}/terraform_${TFVERSION}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

sudo: required

env:
  - MAKE_TASK=test_integration

script:
  - make $MAKE_TASK
